# Generated by Django 3.0.6 on 2020-05-10 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('active', models.BinaryField()),
                ('true_answer', models.CharField(max_length=50, verbose_name='Правильный ответ')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок теста')),
                ('slug', models.SlugField()),
                ('description', models.TextField(max_length=2000, verbose_name='Описание теста')),
                ('active', models.BooleanField()),
                ('admin_comment', models.CharField(max_length=255, verbose_name='Комментарий адмиристратора')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField()),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('active', models.BooleanField()),
                ('admin_comment', models.CharField(max_length=255, verbose_name='Комментарий администратора')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Test')),
            ],
        ),
    ]
