# Generated by Django 3.0.6 on 2020-05-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.RemoveField(
            model_name='poll',
            name='test',
        ),
        migrations.AddField(
            model_name='poll',
            name='test',
            field=models.ManyToManyField(to='polls.Test'),
        ),
        migrations.RemoveField(
            model_name='test',
            name='question',
        ),
        migrations.AddField(
            model_name='test',
            name='question',
            field=models.ManyToManyField(to='polls.Question'),
        ),
    ]
